debug: false

server:
  error:
    whitelabel:
      enabled: false
  max-http-header-size: 8KB
  port: ${JAVA_PG_CORE_SERVER_PORT}

spring:
  datasource:
    url: ${JAVA_PG_CORE_DB_URL}
    username: ${JAVA_PG_CORE_SQL_USER}
    password: ${JAVA_PG_CORE_SQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
